"""State definitions for the market intelligence pipeline.

This module declares the strict Pydantic data models that flow through the
graph, and the LangGraph ``TypedDict`` that is persisted across nodes and
checkpoints.

Design notes
------------
* :class:`CompetitorMetrics` is the strict structured-output schema produced
  by the analyzer via ``with_structured_output`` (Pydantic v2). Unknown or
  missing LLM fields are tolerated (``extra="ignore"`` is the v2 default),
  but the schema itself is fully typed.
* :class:`AgentState` uses ``total=False`` so the CLI can kick off a run with
  nothing but ``target_company``; fields are progressively populated by the
  nodes. ``raw_search_data`` is an *accumulator* channel (``operator.add``)
  so that every self-correction loop appends new evidence instead of
  overwriting previous rounds.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class CompetitorMetrics(BaseModel):
    """Strict, typed synthesis of the competitive research findings."""

    company_overview: str = Field(
        default="",
        description="High-level summary of the target company, its products "
        "and its position in the market.",
    )
    pricing_model: Optional[str] = Field(
        default=None,
        description="Pricing model and price points (plans, tiers, per-user "
        "cost, free trial). ``None`` when not found in the research.",
    )
    target_audience: Optional[str] = Field(
        default=None,
        description="Identified ideal customer profile / buyer personas and "
        "the company size or industry segments they serve.",
    )
    key_value_propositions: List[str] = Field(
        default_factory=list,
        description="The differentiators and value propositions that surface "
        "repeatedly in the research.",
    )
    competitors_mentioned: List[str] = Field(
        default_factory=list,
        description="Notable competitors referenced alongside the target.",
    )
    strengths: List[str] = Field(
        default_factory=list,
        description="Documented strengths / areas the market praises.",
    )
    weaknesses: List[str] = Field(
        default_factory=list,
        description="Documented weaknesses / gaps / criticism.",
    )
    market_positioning: Optional[str] = Field(
        default=None,
        description="Analyst framing, market share, or positioning statements.",
    )
    recent_news: List[str] = Field(
        default_factory=list,
        description="Recent announcements or press items from the research.",
    )
    source_urls: List[str] = Field(
        default_factory=list,
        description="Deduplicated URLs the synthesis was derived from.",
    )


class ResearchReport(BaseModel):
    """Final, machine-readable research report emitted by the pipeline."""

    target_company: str = Field(description="Company under investigation.")
    metrics: CompetitorMetrics = Field(
        description="The structured insights approved for the report."
    )
    research_queries: List[str] = Field(
        default_factory=list,
        description="Every web query issued across all research iterations.",
    )
    iteration_count: int = Field(
        default=0,
        description="Number of self-correction loops executed.",
    )
    quality_score: float = Field(
        default=0.0,
        description="Evaluator quality score in the range [0.0, 1.0].",
    )
    feedback: str = Field(
        default="",
        description="Final evaluator feedback, or the rejection reason.",
    )
    generated_at: str = Field(
        default="",
        description="ISO-8601 timestamp of report generation.",
    )


class OutreachDraft(BaseModel):
    """B2B outreach artifacts generated by the drafter."""

    intelligence_summary: str = Field(
        description="Markdown executive intelligence report the sales team "
        "reads before outreach."
    )
    cold_outreach_email: str = Field(
        description="High-converting, personalized cold outreach email draft."
    )
    recommended_follow_ups: List[str] = Field(
        default_factory=list,
        description="Suggested follow-up plays / cadence steps.",
    )


class AgentState(TypedDict, total=False):
    """The shared, checkpointed state threaded through the entire graph."""

    target_company: str
    raw_search_data: Annotated[List[dict], operator.add]
    structured_insights: Optional[CompetitorMetrics]
    quality_score: float
    feedback: str
    human_approved: bool
    final_report: Optional[str]
    iteration_count: int
